### PR TITLE
change copsOnline

### PR DESCRIPTION
**Pull request by i-kulgu**
Change the copsOnline logic into police:SetCopCount event.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by tom-osborne** [comment]
Why?

**Comment by i-kulgu** [comment]
> Why?

When you use the job type LEO then it won't count you as an online cop because your job name is different.
This way it will set the online cops count to the correct amount even if your job name is BCSO or SASP or any other LEO job.

**Comment by tom-osborne** [comment]
Thanks. Firstly, it would have been worth adding that to the PR description for context.

Secondly, it would make more sense to update the existing core function to handle job types.

**Comment by i-kulgu** [comment]
It was a small change so i just added what was changed in the description.
Will add detailed info the next time..

This was the last copsOnline function that was working like this.
All the other resources (shoprobbery, truckrobbery, houserobbery etc.) are working with the event handler named police:SetCopCount that gets triggered from policejobs every time a player goes on duty / off duty.

I see that there are 2 functions inside core :

QBCore.Functions.GetDutyCount(job)
QBCore.Functions.GetPlayersOnDuty(job)

I'll update those 2 functions so you can do it from there and update all of the other resources to use those functions.

What do you want me to do with this PR ?

**Review by Z3rio — CHANGES_REQUESTED** [review]
`police:SetCopCount` is only triggered on the client, not serverside. (Check qb-policejob/server/main.lua)
image

**Pull request closed without merging**
