### PR TITLE
Added progressbar & in-vehicle condition

### PR DESCRIPTION
**Pull request by arsh939**
**Describe Pull request**
Added a progressbar while selling drugs to ped in cornerselling and added a simple condition which checks whether the player is in a vehicle or not.
Added locales for the same.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **YES**
- Does your code fit the style guidelines? **YES**
- Does your PR fit the contribution guidelines? **YES**

### CODE REVIEW

**Review by HarshZode — APPROVED** [review]

**Review by singh-manavv — APPROVED** [review]

**Review by tom-osborne — CHANGES_REQUESTED** [review]
Please can you fix the indentation in this code? It should be indented with 4 spaces. no tabs.

Also, it looks like you have only updated the code for when qb-target is being used. Can you also update the code for when users are not using qb-target?

Thanks

**Comment by arsh939** [comment]
Did some changes in the conditions and also added the same conditions for users not using qb-target.

**Review by kinglion014 — APPROVED** [review]

**Review by HarshZode — APPROVED** [review]

**Comment by tom-osborne** [comment]
@arsh939 Indentations not fixed

**Comment by arsh939** [comment]
Indentations fixed, @tom-osborne

**Comment by BloodLine1002** [comment]
Nice !!

**Comment by tom-osborne** [comment]
@arsh939 Tested this tonight. Nice PR thanks. The progressbar works nicely and is a good addition.

I do however think that the in-vehicle condition should also prevent the F1 toggle and not allow people to "begin cornerselling". 

Could you add that functionality to this PR? What do you think?

**Review by HarshZode — APPROVED** [review]

**Review by tom-osborne — APPROVED** [review]

**Pull request merged**
