### PR TITLE
Translation management

### PR DESCRIPTION
**Pull request by lunatrik**
Added files to manage translation in en and it. Also added translation logic

### CODE REVIEW

**Review by lunatrik — COMMENTED** [review]
I have checked all my request and now is sync with original repository

**Comment by lunatrik** [comment]
Update with new changes

**Review by lunatrik — COMMENTED** [review]
Review files

**Review by lunatrik — COMMENTED** [review]
correct translations from main project

**Review by sergiotgserra — APPROVED** [review]

**Review by sergiotgserra — APPROVED** [review]

**Pull request closed without merging**
