### PR TITLE
Nearby Deliveries Addition (+1 Bug Fix) 

### PR DESCRIPTION
**Pull request by ae453**
**Describe Pull request**
One issue was fixed in the crossfire, though besides that no other issues were fixed / changed. There was an issue with the line `if #Config.Dealers == 0 then return end` in `client\deliveries.lua` (`InitZones()` Function) that wouldn't allow for the prompt to show up for the dealers, despite showing in the database. Removing that line of code fixed the issue though.

The main functions of this PR is for nearby deliveries. This adds allows server owners to tweak the delivery locations that the user can receive depending on their location.

For example, say there's a dealer in Sandy Shores, with their own respective delivery locations. Upon requesting a delivery job from a dealer, it will take the player's location and randomly pick a delivery location within 2000 units (default, which can be changed in the config). If there's a dealer in Paleto with out any delivery locations within 2000 units, then a notify will show up saying there are no available deliveries. 

This feature allows for servers that use the traditional AOP system keep players in the proper area. Though, if a server does not have an AOP system, you can turn off this functionality completely inside the config, and the resource will work as if the code was never touched.

Also added in a lesser important feature in the config - debug. This can be tied in with other functions within the resource, but currently I only made it to print the location and vector3 of the delivery location to confirm the resource was working as intended.

**Modified Files**
1. `\config.lua`
    - Added Debug, NearbyDeliveries, and DeliveryWithin. 
2. `\client\deliveries.lua`
    - Functionality for the nearby deliveries was added here.
3. `\locales\*`
    - I added custom messages for the added notifies.
    - Since I only speak English, I can only provide the English translation, but the locale variable is given inside each of the files, I just don't know any of the other languages, and I do remember how bad Google Translate translations are.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
    - Yes, I tried my best to do as much testing. With it as possible. Though, I did come across an issue while using NPWD. Using qb-phone everything worked as intended.
- Does your code fit the style guidelines?
    - Yes.
- Does your PR fit the contribution guidelines?
    - In my opinion, I believe that this PR follows the guidelines closely.

### CODE REVIEW

**Comment by ae453** [comment]
Fixed all checks 🥳

**Comment by MentalIllness** [comment]
Thanks for opening this pull request and updating it to be compatible with the latest updates. After revealing your commits, I decided to put them in the merge queue so they should be merged as soon as possible.

**Review by MentalIllness — APPROVED** [review]
Approved

**Comment by ae453** [comment]
> Thanks for opening this pull request and updating it to be compatible with the latest updates. After revealing your commits, I decided to put them in the merge queue so they should be merged as soon as possible.

Thanks for the reply! In the future I hope to add more to the script.

**Pull request merged**
